[project]
name = "hangman-with-tdd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flake8>=7.3.0",
    "pylint>=3.3.8",
    "pytest>=8.4.1",
]
